# Change FROM to python:3.8-alpine to test without the dependencies container
FROM dragonchain/dragonchain_core_dependencies:latest as base

# Install Helm for chart linting and/or yq for doc builds if it doesn't exist
RUN if ! command -v helm; then \
    wget -O helm-v2.14.3-linux-arm64.tar.gz 'https://get.helm.sh/helm-v2.14.3-linux-arm64.tar.gz' && \
    tar xzf helm-v2.14.3-linux-arm64.tar.gz && mv linux-arm64/helm /usr/local/bin/helm && \
    rm -rf helm-v2.14.3-linux-arm64.tar.gz linux-arm64; fi && \
    helm init --client-only && \
    if ! command -v yq; then \
    wget -O yq 'https://github.com/mikefarah/yq/releases/download/2.4.1/yq_linux_arm64' && \
    chmod +x yq && mv yq /usr/local/bin/; fi

WORKDIR /usr/src/core
# Install necessary base dependencies and set UTC timezone for apscheduler
RUN apk --no-cache upgrade && apk --no-cache add libffi libstdc++ gmp && echo "UTC" > /etc/timezone

FROM base AS builder
# Install dev build dependencies
RUN apk add g++ make gmp-dev libffi-dev automake autoconf libtool
# Install python dev dependencies
ENV SECP_BUNDLED_EXPERIMENTAL 1
ENV SECP_BUNDLED_WITH_BIGNUM 1
COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt
COPY dev_requirements.txt .
RUN python3 -m pip install --upgrade -r dev_requirements.txt

FROM base AS release
# Copy the installed python dependencies from the builder
COPY --from=builder /usr/local/lib/python3.8/site-packages /usr/local/lib/python3.8/site-packages
# Sphinx is needed to build the docs
COPY --from=builder /usr/local/bin/sphinx-build /usr/local/bin/sphinx-build
# Copy our actual application
COPY --chown=1000:1000 . .
RUN chmod 777 .

CMD [ "sh", "tools.sh", "full-test" ]
