version: '2'
services:
  db:
    build:
      dockerfile: docker/Postgres_Dockerfile
      context: ../
    ports:
      - "5433:5433"

  query_svc:
    build:
      dockerfile: docker/Query_Dockerfile
      context: ../
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - BLOCKCHAIN_DB_HOSTNAME=db
    volumes:
      - keyvolume:/opt/dragonchain/pki

  txn_service:
    build:
      dockerfile: docker/Transaction_Dockerfile
      context: ../
    ports:
      - "81:81"
    depends_on:
      - db
    environment:
      - BLOCKCHAIN_DB_HOSTNAME=db
    volumes:
      - keyvolume:/opt/dragonchain/pki

  processor1:
    build:
      dockerfile: docker/Processor_Dockerfile
      context: ../
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - BLOCKCHAIN_DB_HOSTNAME=db
    volumes:
      - keyvolume:/opt/dragonchain/pki
      - ~/configs/node1:/opt/dragonchain/configs

  processor2:
    build:
      dockerfile: docker/Processor_Dockerfile
      context: ../
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - BLOCKCHAIN_DB_HOSTNAME=db
    volumes:
      - keyvolume:/opt/dragonchain/pki
      - ~/configs/node2:/opt/dragonchain/configs

volumes:
    keyvolume:
      driver: local