FROM {customerBaseImage}

# Install function watchdog
COPY bin/fwatchdog /usr/bin/fwatchdog

# Set non-root user
USER 1000:1000

# Set process
ENV write_debug="false"

# Ensure no entrypoint
ENTRYPOINT []

# Set up function entry point
EXPOSE 8080
HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1
CMD [ "/usr/bin/fwatchdog" ]

# Add random entropy to container to gaurentee that it has a unique digest hash
ENV {entropy}=""
